// Generated by ts-to-zod
import { z } from "zod";

export const chunkImageParamsSchema = z.object({
  fileUuid: z.number(),
  fileIndex: z.number(),
  file: z
    .instanceof(File)
    .or(z.string())
    .openapi({ type: "array", items: { type: "string", format: "binary" } }),
});
