// Generated by ts-to-zod
import { z } from "zod";

import { userDataSchema } from "./../user/schemas";

export const loginParamsSchema = z.object({
  username: z.string(),
  password: z.string(),
});

export const loginDataSchema = z.object({
  data: z.object({
    tokens: z.string(),
    user: userDataSchema.omit({ password: true }),
  }),
});

export const profileDataSchema = z.object({
  data: userDataSchema.omit({ password: true }),
});

export const getProfileParamsSchema = z.object({
  id: z.number(),
});
