// Generated by ts-to-zod
import { z } from "zod";

import {
  queryPaginationDataSchema,
  queryPaginationOptionsSchema,
} from "./../../general";

export const simpleTodoDataSchema = z.object({
  id: z.number(),
  name: z.string(),
  isCompleted: z.boolean(),
});

export const getSimpleTodoListParamsSchema = queryPaginationOptionsSchema;

export const getSimpleTodoListDataSchema = z.object({
  data: z.array(simpleTodoDataSchema),
  meta: queryPaginationDataSchema,
});

export const getSimpleTodoDetailParamsSchema = z.object({
  id: z.coerce.number(),
});

export const getSimpleTodoDetailDataSchema = z.object({
  data: simpleTodoDataSchema,
});

export const createSimpleTodoParamsSchema = z.object({
  name: z.string(),
});

export const createSimpleTodoDataSchema = z.object({
  data: simpleTodoDataSchema,
});

export const updateSimpleTodoParamsSchema = z.object({
  id: z.coerce.number(),
  name: z.string().optional(),
});

export const updateSimpleTodoDataSchema = z.object({
  data: simpleTodoDataSchema,
});

export const deleteSimpleTodoParamsSchema = z.object({
  id: z.coerce.number(),
});

export const deleteSimpleTodoDataSchema = z.object({
  data: z.object({
    id: z.coerce.number(),
  }),
});
