// Generated by ts-to-zod
import { z } from "zod";

import {
  queryPaginationDataSchema,
  queryPaginationOptionsSchema,
} from "../../general";

export const productDataSchema = z.object({
  id: z.number(),
  name: z.string().nullable(),
  desc: z.string(),
});

export const getProductsFilterSchema = z.object({
  name: z.string().optional(),
});

export const getProductsParamsSchema = getProductsFilterSchema.extend(
  queryPaginationOptionsSchema.shape,
);

export const getProductsDataSchema = z.object({
  data: z.array(productDataSchema),
  meta: queryPaginationDataSchema,
});

export const getProductParamsSchema = z.object({
  id: z.coerce.number(),
});

export const getProductDataSchema = z.object({
  data: productDataSchema,
});

export const updateProductParamsSchema = z.object({
  id: z.coerce.number(),
  name: z.string().optional(),
  desc: z.string().optional(),
});

export const updateProductDataSchema = z.object({
  data: productDataSchema,
});

export const deleteProductParamsSchema = z.object({
  id: z.coerce.number(),
});

export const deleteProductDataSchema = z.object({
  data: z.object({
    id: z.coerce.number(),
  }),
});
